apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tooling.artifactory.peterdada.me
  namespace: tools
spec:
  dnsNames:
  - tooling.artifactory.peterdada.me
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: aws-route53-creds
  usages:
  - digital signature
  - key encipherment