---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: artifactory.peterdada.me
  # cert-manager will put the resulting Secret in the same Kubernetes
  # namespace as the Certificate. You should create the certificate in
  # whichever namespace you want to configure a Host.
spec:
  secretName: artifactory.peterdada.me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: artifactory.peterdada.me
  dnsNames:
  - artifactory.peterdada.me
